### ISSUE TITLE
#define that messes other stuff

### ISSUE THREAD

**Issue by roymacdonald** [moebiussurfing/ofxSurfingImGui#16]
Hi Manu,
The #define at
https://github.com/moebiussurfing/ofxSurfingImGui/blob/master/src/ImGui/themes/SurfingThemes.h#L36

is messing up other includes. It does not look like a really necessary thing to have in this addon, so, if you can please remove it.
best

**Comment by moebiussurfing** [comment]
Thanks for catching. I just fixed and pushed that. 

PS:

I recently removed the `ofxSurfingHelpers` addon dependency from `ofxSurfingImGui`,
and moved the required functions to `addons\ofxSurfingImGui\src\ImGui\utils\surfingHelpers.h`

so if you pulled recently, you could notice maybe some namespace conflicts between:
`ofxImGuiSurfing::` / `ofxSurfingHelpers::`.

I am dealing to not break some projects, but I don't found a clean mode yet.
So I am using some “dirty workarounds” like `namespace ofxSurfingHelpers = ofxImGuiSurfing;`
